name: "Clean Up Git History"

on:
  push:
    branches:
      - master  # Or the branch you want to clean up
  workflow_dispatch:

jobs:
  cleanup-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Fetch only the latest commit

      - name: Set up Git user
        run: |
          git config --global user.email "actions-bot@example.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Remove Git history and keep the latest commit
        run: |
          git checkout --orphan latest_commit   # Create a new orphan branch
          git add -A                            # Stage all files
          git commit -m "Preserve the latest commit"   # Commit all files as a new commit
          git branch -D master                    # Delete the old branch
          git branch -m master                    # Rename the current branch to 'main'
          git push --force --set-upstream origin master  # Force-push to update remote history

      - name: Verify Git history cleanup
        run: git log --oneline --graph --decorate --all
